name: liquid_glass_ui
description: A Flutter package for creating beautiful glass-like UI components inspired by Apple's Liquid Glass design.
version: 0.4.0
homepage: https://github.com/prdalai/liquid_glass_ui

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true 